
# dataSource
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://myserver:8505/mydb?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8

# log level
logging:
  level:
    com.jiang: debug



